# ===== Simulación =====
# Tiempo total de simulación en segundos
T=30
# ===== Restaurante =====
# Cantidad de mesas
M=5
# Personas por mesa
P=4
# Cantidad de mozos
Z=2
# Cantidad de cocineros
C=2
# Cantidad de cajeros
Y=1

# ===== Clientes =====
# Tiempo mínimo/máximo entre llegadas de clientes (ms)
TPmin=1500
TPmax=3000
# Tiempo mínimo/máximo seleccionando menú (ms)
TMmin=800
TMmax=2000
# Tiempo mínimo/máximo comiendo (ms)
TQmin=3000
TQmax=6000

# ===== Mozos =====
# Tiempo mínimo/máximo anotando pedido e ir a cocina (ms)
TZmin=800
TZmax=2000
# Tiempo mínimo/máximo retirando platos y sirviendo (ms)
TRmin=1000
TRmax=2500
# Tiempo mínimo/máximo levantando platos y limpiando mesa (ms)
TLmin=1000
TLmax=2500

# ===== Cocineros =====
# Tiempo mínimo/máximo por defecto de cocción (si el menú no define el suyo) (ms)
TCmin=2000
TCMax=5000

# ===== Cajeros =====
# Tiempo mínimo/máximo cobrando (ms)
TYmin=1000
TYmax=2000